# Generated by Django 2.2 on 2019-04-16 00:25

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_name', models.CharField(max_length=40)),
                ('materials_used', models.CharField(choices=[('Lumber', 'LUMBER'), ('Steel', 'STEEL'), ('Shingles', 'SHINGLES'), ('Nails', 'NAILS')], max_length=10)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('time_submitted', models.DateTimeField(default=datetime.datetime.now)),
                ('date_submitted', models.DateField(default=datetime.datetime.today)),
            ],
            options={
                'ordering': ('-time_submitted',),
            },
        ),
        migrations.CreateModel(
            name='ClockOutModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=40)),
                ('time_departed', models.DateTimeField(default=datetime.datetime.now)),
                ('date_submitted', models.DateField(default=datetime.datetime.today)),
            ],
            options={
                'unique_together': {('employee_name', 'date_submitted')},
            },
        ),
        migrations.CreateModel(
            name='ClockInModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=40)),
                ('time_arrived', models.DateTimeField(default=datetime.datetime.now)),
                ('date_submitted', models.DateField(default=datetime.datetime.today)),
            ],
            options={
                'unique_together': {('employee_name', 'date_submitted')},
            },
        ),
    ]
