# Generated by Django 2.2 on 2019-04-16 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clockinmodel',
            options={'ordering': ('date_submitted',)},
        ),
        migrations.AlterModelOptions(
            name='clockoutmodel',
            options={'ordering': ('-date_submitted',)},
        ),
    ]
